pnc-virtual-company/2018-inventory

- application/controllers/Connection.php
> [IN02] Remove comment in connection

- application/controllers/Connection.php
> [IN03] Add comment on connection file

- application/config/routes.php
- application/controllers/Connection.php
> [IN007] config default rout to connection/login

- application/views/menu/index.php
- application/views/templates/header.php
> [IN001] update header layout

- application/controllers/Connection.php
- application/controllers/Users.php
- application/views/items/create.php
- application/views/menu/index.php
> [IN005] Update items layout

- application/controllers/models.php
- application/views/menu/index.php
- application/views/models/create.php
- application/views/models/edit.php
- application/views/models/index.html
- application/views/models/index.php
> [IN009]Create model layout

- application/controllers/category.php
- application/views/category/index.php
> [IN013] fix create edit and delete on category

- application/controllers/Owner.php
- application/controllers/brand.php
- application/controllers/locations.php
- application/controllers/models.php
- application/views/brands/index.html
- application/views/brands/index.php
- application/views/category/index.php
- application/views/departments/index.php
- application/views/locations/index.php
- application/views/login/login.php
- application/views/materials/index.php
- application/views/models/index.php
- application/views/templates/header.php
> [IN008] create brand layout and check other files

- application/controllers/materials.php
- application/models/Materials_model.php
- application/models/Users_model.php
- application/models/items_model.php
- application/views/materials/index.php
> [IN016] CRUD material

- application/controllers/Departments.php
- application/controllers/brand.php
- application/models/brand_model.php
- application/models/department_model.php
- application/views/brands/index.php
- application/views/departments/index.php
> [IN018] Crud brand

- application/controllers/items.php
- application/controllers/locations.php
- application/models/items_model.php
- application/views/items/index.php
> [IN022] Select and Delete Items

- application/views/items/index.php
> [IN025] Add datatable plugin reorder

- README.md
- application/config/config.php
- application/views/menu/index.php
> [IN027] Change cookie and Add ReadMe file

- application/views/errors/html/notfound.php
- application/views/reports/charts.php
> [IN030] chage number in file reports and error in file not found

- application/controllers/items.php
- application/models/items_model.php
- application/views/brands/index.php
- application/views/category/index.php
- application/views/departments/index.php
- application/views/items/create.php
- application/views/items/index.php
- application/views/locations/index.php
- application/views/materials/index.php
- application/views/menu/index.php
- application/views/models/index.php
- application/views/owners/index.php
- application/views/reports/charts.php
> [IN023] Create item and fix some spelling mistake

- application/controllers/items.php
- application/models/items_model.php
- application/views/items/edit.php
- application/views/items/index.php
- application/views/menu/index.php
> [IN024] Update item and edit some style

- application/controllers/items.php
- application/models/items_model.php
- application/views/items/index.php
> [IN031] Create modal show detail item styling vis

- application/controllers/items.php
- application/views/items/create.php
- application/views/items/edit.php
- application/views/items/index.php
- application/views/menu/index.php
> [IN034] Update all item form and styling

- application/controllers/Departments.php
- application/controllers/materials.php
- application/models/Users_model.php
- application/views/brands/index.php
- application/views/category/index.php
- application/views/departments/index.php
- application/views/locations/index.php
- application/views/materials/index.php
- application/views/models/index.php
- application/views/owners/index.php
> [IN036] fix error spelling and styling

- application/models/Users_model.php
> [IN0200] solve conflict on file users_model

- application/controllers/items.php
- application/models/items_model.php
- application/views/items/create.php
- application/views/items/edit.php
> [IN042] Fix form item

- application/views/reports/charts.php
> [IN0300] put value above bar chart

- application/controllers/borrow.php
- application/models/borrow_model.php
- application/views/borrow/index.php
- application/views/items/index.php
- application/views/menu/index.php
> [IN044] Create borrow list page

- application/models/items_model.php
> [IN01100] add model to item model for export item

- application/views/items/index.php
> [IN035] Create advance filter

- Jenkinsfile
- application/controllers/Items.php
- application/controllers/Reports.php
- application/controllers/Status.php
- application/models/Items_model.php
- application/models/Reports_model.php
- application/models/Status_model.php
- application/views/items/edit.php
- application/views/items/export.php
- application/views/items/index.php
- application/views/menu/index.php
- application/views/reports/charts.php
- application/views/status/index.php
- assets/js/item-script.js
- sql/inventory.sql
- define a new attribute for an item: status
- old status is now called borrow status
- add new status to report
- status different to 'In stock' cannot be borrowed
> Manage status for items
